//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWcfClient.NbpRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NbpRef.IExchangeRateService")]
    public interface IExchangeRateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeRateService/GetExchangeRate", ReplyAction="http://tempuri.org/IExchangeRateService/GetExchangeRateResponse")]
        decimal GetExchangeRate(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeRateService/GetExchangeRate", ReplyAction="http://tempuri.org/IExchangeRateService/GetExchangeRateResponse")]
        System.Threading.Tasks.Task<decimal> GetExchangeRateAsync(string currencyCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExchangeRateServiceChannel : HelloWcfClient.NbpRef.IExchangeRateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExchangeRateServiceClient : System.ServiceModel.ClientBase<HelloWcfClient.NbpRef.IExchangeRateService>, HelloWcfClient.NbpRef.IExchangeRateService {
        
        public ExchangeRateServiceClient() {
        }
        
        public ExchangeRateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExchangeRateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExchangeRateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExchangeRateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal GetExchangeRate(string currencyCode) {
            return base.Channel.GetExchangeRate(currencyCode);
        }
        
        public System.Threading.Tasks.Task<decimal> GetExchangeRateAsync(string currencyCode) {
            return base.Channel.GetExchangeRateAsync(currencyCode);
        }
    }
}
