//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeOffice.TestClient.ExchangeOfficeRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionDto", Namespace="http://schemas.datacontract.org/2004/07/ExchangeOffice.Contracts")]
    [System.SerializableAttribute()]
    public partial class TransactionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RatePointDto", Namespace="http://schemas.datacontract.org/2004/07/ExchangeOffice.Contracts")]
    [System.SerializableAttribute()]
    public partial class RatePointDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExchangeOfficeRef.IExchangeOfficeService")]
    public interface IExchangeOfficeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeOfficeService/GetCurrentRate", ReplyAction="http://tempuri.org/IExchangeOfficeService/GetCurrentRateResponse")]
        decimal GetCurrentRate(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeOfficeService/GetCurrentRate", ReplyAction="http://tempuri.org/IExchangeOfficeService/GetCurrentRateResponse")]
        System.Threading.Tasks.Task<decimal> GetCurrentRateAsync(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeOfficeService/RegisterUser", ReplyAction="http://tempuri.org/IExchangeOfficeService/RegisterUserResponse")]
        int RegisterUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeOfficeService/RegisterUser", ReplyAction="http://tempuri.org/IExchangeOfficeService/RegisterUserResponse")]
        System.Threading.Tasks.Task<int> RegisterUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeOfficeService/TopUpPln", ReplyAction="http://tempuri.org/IExchangeOfficeService/TopUpPlnResponse")]
        void TopUpPln(int userId, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeOfficeService/TopUpPln", ReplyAction="http://tempuri.org/IExchangeOfficeService/TopUpPlnResponse")]
        System.Threading.Tasks.Task TopUpPlnAsync(int userId, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeOfficeService/BuyCurrency", ReplyAction="http://tempuri.org/IExchangeOfficeService/BuyCurrencyResponse")]
        void BuyCurrency(int userId, string currencyCode, decimal foreignAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeOfficeService/BuyCurrency", ReplyAction="http://tempuri.org/IExchangeOfficeService/BuyCurrencyResponse")]
        System.Threading.Tasks.Task BuyCurrencyAsync(int userId, string currencyCode, decimal foreignAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeOfficeService/SellCurrency", ReplyAction="http://tempuri.org/IExchangeOfficeService/SellCurrencyResponse")]
        void SellCurrency(int userId, string currencyCode, decimal foreignAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeOfficeService/SellCurrency", ReplyAction="http://tempuri.org/IExchangeOfficeService/SellCurrencyResponse")]
        System.Threading.Tasks.Task SellCurrencyAsync(int userId, string currencyCode, decimal foreignAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeOfficeService/GetBalance", ReplyAction="http://tempuri.org/IExchangeOfficeService/GetBalanceResponse")]
        decimal GetBalance(int userId, string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeOfficeService/GetBalance", ReplyAction="http://tempuri.org/IExchangeOfficeService/GetBalanceResponse")]
        System.Threading.Tasks.Task<decimal> GetBalanceAsync(int userId, string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeOfficeService/GetTransactionHistory", ReplyAction="http://tempuri.org/IExchangeOfficeService/GetTransactionHistoryResponse")]
        ExchangeOffice.TestClient.ExchangeOfficeRef.TransactionDto[] GetTransactionHistory(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeOfficeService/GetTransactionHistory", ReplyAction="http://tempuri.org/IExchangeOfficeService/GetTransactionHistoryResponse")]
        System.Threading.Tasks.Task<ExchangeOffice.TestClient.ExchangeOfficeRef.TransactionDto[]> GetTransactionHistoryAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeOfficeService/GetHistoricalRates", ReplyAction="http://tempuri.org/IExchangeOfficeService/GetHistoricalRatesResponse")]
        ExchangeOffice.TestClient.ExchangeOfficeRef.RatePointDto[] GetHistoricalRates(string currencyCode, System.DateTime from, System.DateTime to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeOfficeService/GetHistoricalRates", ReplyAction="http://tempuri.org/IExchangeOfficeService/GetHistoricalRatesResponse")]
        System.Threading.Tasks.Task<ExchangeOffice.TestClient.ExchangeOfficeRef.RatePointDto[]> GetHistoricalRatesAsync(string currencyCode, System.DateTime from, System.DateTime to);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExchangeOfficeServiceChannel : ExchangeOffice.TestClient.ExchangeOfficeRef.IExchangeOfficeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExchangeOfficeServiceClient : System.ServiceModel.ClientBase<ExchangeOffice.TestClient.ExchangeOfficeRef.IExchangeOfficeService>, ExchangeOffice.TestClient.ExchangeOfficeRef.IExchangeOfficeService {
        
        public ExchangeOfficeServiceClient() {
        }
        
        public ExchangeOfficeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExchangeOfficeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExchangeOfficeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExchangeOfficeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal GetCurrentRate(string currencyCode) {
            return base.Channel.GetCurrentRate(currencyCode);
        }
        
        public System.Threading.Tasks.Task<decimal> GetCurrentRateAsync(string currencyCode) {
            return base.Channel.GetCurrentRateAsync(currencyCode);
        }
        
        public int RegisterUser(string username, string password) {
            return base.Channel.RegisterUser(username, password);
        }
        
        public System.Threading.Tasks.Task<int> RegisterUserAsync(string username, string password) {
            return base.Channel.RegisterUserAsync(username, password);
        }
        
        public void TopUpPln(int userId, decimal amount) {
            base.Channel.TopUpPln(userId, amount);
        }
        
        public System.Threading.Tasks.Task TopUpPlnAsync(int userId, decimal amount) {
            return base.Channel.TopUpPlnAsync(userId, amount);
        }
        
        public void BuyCurrency(int userId, string currencyCode, decimal foreignAmount) {
            base.Channel.BuyCurrency(userId, currencyCode, foreignAmount);
        }
        
        public System.Threading.Tasks.Task BuyCurrencyAsync(int userId, string currencyCode, decimal foreignAmount) {
            return base.Channel.BuyCurrencyAsync(userId, currencyCode, foreignAmount);
        }
        
        public void SellCurrency(int userId, string currencyCode, decimal foreignAmount) {
            base.Channel.SellCurrency(userId, currencyCode, foreignAmount);
        }
        
        public System.Threading.Tasks.Task SellCurrencyAsync(int userId, string currencyCode, decimal foreignAmount) {
            return base.Channel.SellCurrencyAsync(userId, currencyCode, foreignAmount);
        }
        
        public decimal GetBalance(int userId, string currencyCode) {
            return base.Channel.GetBalance(userId, currencyCode);
        }
        
        public System.Threading.Tasks.Task<decimal> GetBalanceAsync(int userId, string currencyCode) {
            return base.Channel.GetBalanceAsync(userId, currencyCode);
        }
        
        public ExchangeOffice.TestClient.ExchangeOfficeRef.TransactionDto[] GetTransactionHistory(int userId) {
            return base.Channel.GetTransactionHistory(userId);
        }
        
        public System.Threading.Tasks.Task<ExchangeOffice.TestClient.ExchangeOfficeRef.TransactionDto[]> GetTransactionHistoryAsync(int userId) {
            return base.Channel.GetTransactionHistoryAsync(userId);
        }
        
        public ExchangeOffice.TestClient.ExchangeOfficeRef.RatePointDto[] GetHistoricalRates(string currencyCode, System.DateTime from, System.DateTime to) {
            return base.Channel.GetHistoricalRates(currencyCode, from, to);
        }
        
        public System.Threading.Tasks.Task<ExchangeOffice.TestClient.ExchangeOfficeRef.RatePointDto[]> GetHistoricalRatesAsync(string currencyCode, System.DateTime from, System.DateTime to) {
            return base.Channel.GetHistoricalRatesAsync(currencyCode, from, to);
        }
    }
}
