CREATE TABLE Users (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Username NVARCHAR(50) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(200) NOT NULL
);

CREATE TABLE Balances (
  UserId INT NOT NULL,
  CurrencyCode NVARCHAR(3) NOT NULL,
  Amount DECIMAL(18,4) NOT NULL,
  CONSTRAINT PK_Balances PRIMARY KEY (UserId, CurrencyCode),
  CONSTRAINT FK_Balances_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE Transactions (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  UserId INT NOT NULL,
  [Date] DATETIME2 NOT NULL,
  [Type] NVARCHAR(10) NOT NULL,
  CurrencyCode NVARCHAR(3) NOT NULL,
  Amount DECIMAL(18,4) NOT NULL,
  Rate DECIMAL(18,6) NOT NULL,
  CONSTRAINT FK_Transactions_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);